version: '2'
services:
  jupyter:
    build: ./docker
    ports:
      - 8888:8888
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./notebooks/ri-notebooks:/home/jovyan/work/ri-notebooks
      - ./notebooks/planning_control_notebooks:/home/jovyan/work/planning_control_notebooks
    networks:
      default:
        aliases:
          - jupyter.local

